### ISSUE TITLE
Speed issues

### ISSUE THREAD

**Issue by reishikin** [bnsantoso/sub-to-audio#6]
Hello! First off, thank you for the fantastic update. 

I've been experimenting with controlling the tempo using both the overflow and all modes. However, I've noticed that when the subtitle is lengthy and the time duration is quite brief, the audio and subtitle don't seem to sync up properly even when overflow mode is used. Do you have any suggestions or solutions to address this issue?

**Comment by bnsantoso** [comment]
For clarity, how severe is the out-of-sync issue? How far is the audio from its actual time position? I don't know which problem you are facing, so I assume it could be either that the audio does not match the start point or that the audio exceeds the end point, or perhaps both.

The reason the audio is not in sync at the start point is that the time shifter tries to avoid overlapping audio positions. The shifter adjusts both the start point and end point until it finds a blank time that can buffer the shift. Unfortunately, subtoaudio doesn't currently have an option to disable the shifter. well you can delete or comment [this](https://github.com/bnsantoso/sub-to-audio/blob/f8cd81bb19612f5571bd65b913b9c32658608d91/subtoaudio/subtoaudio.py#L114) for workaround.

If your issue is that the audio does not match the end point, I think it's due to the overflow mode compressing the audio time to match `sub_duration`. The variable `sub_duration` is the sum of how long the actual subtitle appears and the blank time before the next subtitle appears. Therefore, it doesn't match the end point since I use the blank time as a buffer for the audio. and if you using `tempo_limit` or `tempo_speed` param and the audio length is still to long, it will trigger the time shifter to. 

Sorry for the inconvenience when using this script. i hope this can explain why the issue happen.

To address the issue, try manually editing the subtitles with fewer words but retaining the same meaning. I suggest using Aegisub; it can tell you if the subtitle word count is too long for the actual subtitle duration and can inform you that some subtitle is overlaping. overlaping subtitle can cause big out-of-sync, so make sure to check.

For future plan maybe i will add shifting mode and more tempo control mode.

**Comment by bnsantoso** [comment]
The latest update, I believe, should be able to solve your issue. I've added several shift modes and one more tempo mode, namely "`precise`" , which will make the audio duration match the duration of the displayed subtitles. I hope this can resolve your problem. Thank you for your support.
